apiVersion: v1
kind: Service
metadata:
  name: httpbin-svc
spec:
  externalName: httpbin.org
  type: ExternalName
  ports:
  - name: http
    port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: httpbin-ingress
spec:
  rules:
  - host: k8s-external-name-svc-spike.io
    http:
      paths:
      - backend:
          serviceName: httpbin-svc
          servicePort: 80
        path: /
