apiVersion: v1
kind: Service
metadata:
  name: httpbin-ssl-svc
spec:
  type: ExternalName
  externalName: httpbin.org
  ports:
  - name: https
    port: 443
    targetPort: 443
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: httpbin-ssl-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
  - hosts:
    - k8s-external-name-svc-spike.io
  rules:
  - host: k8s-external-name-svc-spike.io
    http:
      paths:
      - backend:
          serviceName: httpbin-ssl-svc
          servicePort: 443
        path: /
